In [10]:
import pandas as pd  
  
# 从第一个表格中抽取指定列  
file1_columns = ["年份", "季度", "证券代码", "公司发布财报的日期", "财报统计的季度的最后一天", "流动比率", "速动比率", "现金比率", "总负债同比增长率", "资产负债率", "权益乘数"]  
file1 = pd.read_excel("1.xlsx", usecols=file1_columns)  
assert set(file1_columns).issubset(file1.columns), "Some columns are missing in file1"  
  
# 从第二个表格中抽取指定列  
file2_columns = ["流动资产除以总资产", "有形资产除以总资产", "已获利息倍数", "经营活动产生的现金流量净额除以营业收入", "经营性现金净流量除以净利润", "	经营性现金净流量除以营业总收入"]  
file2 = pd.read_excel("2.xlsx", usecols=file2_columns)  
assert set(file2_columns).issubset(file2.columns), "Some columns are missing in file2"  
  
# 从第三个表格中抽取指定列  
file3_columns = ["净资产收益率(平均)(%)", "销售净利率(%)", "销售毛利率(%)", "净利润(元)", "每股收益", "主营营业收入(元)", "总股本", "流通股本"]  
file3 = pd.read_excel("3.xlsx", usecols=file3_columns)  
assert set(file3_columns).issubset(file3.columns), "Some columns are missing in file3"  


# 将抽取的列数据合并到一个新的DataFrame  
merged_data = pd.concat([file1, file2, file3], axis=0)  

# # 保存合并后的数据到新的Excel文件  
# merged_data.to_excel("merged.xlsx", index=False)

In [11]:
import pandas as pd  
  
# 从第一个表格中抽取指定列  
file1_columns = ["年份", "季度", "证券代码", "公司发布财报的日期", "财报统计的季度的最后一天", "流动比率", "速动比率", "现金比率", "总负债同比增长率", "资产负债率", "权益乘数"]  
file1 = pd.read_excel("1.xlsx", usecols=file1_columns)  
file1

,证券代码,公司发布财报的日期,财报统计的季度的最后一天,流动比率,速动比率,现金比率,总负债同比增长率,资产负债率,权益乘数,年份,季度
0,sh.600031,2007-04-27,2007-03-31,1.930173,1.346049,0.445350,0.203491,0.532653,2.139738,2007,1
1,sh.600031,2007-08-25,2007-06-30,2.124378,1.522433,0.620292,0.768882,0.550989,2.227119,2007,2
2,sh.600031,2007-10-25,2007-09-30,2.050736,1.563713,0.656168,0.999264,0.560575,2.275702,2007,3
3,sh.600031,2008-04-25,2007-12-31,2.061416,1.485198,0.743892,0.880413,0.548513,2.214906,2007,4
4,sh.600031,2008-04-29,2008-03-31,2.017155,1.408942,0.626482,1.007886,0.578640,2.373269,2008,1
...,...,...,...,...,...,...,...,...,...,...,...
62,sh.600031,2022-10-29,2022-09-30,1.619756,1.292459,0.540050,0.253743,0.572634,2.339916,2022,3
63,sh.600031,2023-04-01,2022-12-31,1.563826,1.271969,0.534665,0.262512,0.584209,2.405055,2022,4
64,sh.600031,2023-04-26,2023-03-31,1.667326,1.297028,0.518920,0.161584,0.576093,2.359008,2023,1
65,sh.600031,2023-08-31,2023-06-30,1.631530,1.288360,0.497132,0.089155,0.578957,2.375056,2023,2
66,sh.600031,2023-10-31,2023-09-30,1.687704,1.337780,0.514711,-0.034188,0.553227,2.238272,2023,3

In [12]:
# 从第二个表格中抽取指定列  
file2_columns = ["流动资产除以总资产", "有形资产除以总资产", "已获利息倍数", "经营活动产生的现金流量净额除以营业收入", "经营性现金净流量除以净利润", "	经营性现金净流量除以营业总收入"]  
file2 = pd.read_excel("2.xlsx", usecols=file2_columns)  
file2

,流动资产除以总资产,有形资产除以总资产,已获利息倍数,经营活动产生的现金流量净额除以营业收入,经营性现金净流量除以净利润,\t经营性现金净流量除以营业总收入
0,0.766090,0.424565,13.429921,-0.202886,-0.890592,-0.202886
1,0.756406,0.374344,18.924414,0.084174,0.391510,0.084174
2,0.774842,0.367314,17.854110,0.013123,0.060067,0.013123
3,0.749763,0.382145,15.714407,0.068955,0.330881,0.068955
4,0.766937,0.353397,NaN,-0.075172,-0.568348,-0.075172
...,...,...,...,...,...,...
62,0.682831,0.371490,NaN,0.059538,0.936959,0.058931
63,0.666197,0.361748,NaN,0.051223,0.930567,0.050713
64,0.660840,0.368139,NaN,-0.088274,-1.005534,-0.087248
65,0.661311,0.364972,47.041432,0.010177,0.114945,0.010070
66,0.652928,0.387460,NaN,0.091167,1.220224,0.090170

In [14]:
# 从第三个表格中抽取指定列  
file3_columns = ["净资产收益率(平均)(%)", "销售净利率(%)", "销售毛利率(%)", "净利润(元)", "每股收益", "主营营业收入(元)", "总股本", "流通股本"]  
file3 = pd.read_excel("3.xlsx", usecols=file3_columns)  
file3

,净资产收益率(平均)(%),销售净利率(%),销售毛利率(%),净利润(元),每股收益,主营营业收入(元),总股本,流通股本
0,0.122170,0.227810,0.363769,4.265567e+08,1.871154,NaN,480000000,172936906
1,0.259030,0.214998,0.356096,9.446229e+08,1.207200,4.091868e+09,960000000,441873812
2,0.365067,0.218471,0.352400,1.523897e+09,1.426779,NaN,992000000,441873800
3,0.418673,0.208398,0.345628,1.905785e+09,1.619113,8.355828e+09,992000000,441873800
4,0.062107,0.132264,0.321850,3.524015e+08,1.554807,NaN,992000000,441873800
...,...,...,...,...,...,...,...,...
62,0.056150,0.063544,0.228295,3.721205e+09,0.360699,NaN,8493286021,8470899771
63,0.066422,0.055045,0.240175,4.404585e+09,0.503080,7.810055e+10,8493286021,8470899771
64,0.023008,0.087788,0.276032,1.561535e+09,0.494266,NaN,8486602087,8464215837
65,0.051620,0.088538,0.282146,3.496969e+09,0.593719,3.863273e+10,8486602087,8464215837
66,0.060971,0.074714,0.284954,4.148270e+09,0.556514,NaN,8486602087,8464215837

In [15]:
# 使用pd.concat()函数将两个DataFrame横向合并  
merged_df = pd.concat([file1, file2,file3], axis=1)  
  
# 将合并后的DataFrame保存到新的Excel文件中  
merged_df.to_excel("merged.xlsx", index=False)

In [2]:
import os  
import pandas as pd  
  
# 设置文件夹路径  
folder_path = 'test1'  
  
# 遍历文件夹中的Excel文件  
for filename in os.listdir(folder_path):  
    if filename.endswith(".xlsx") or filename.endswith(".xls"):  
        file_path = os.path.join(folder_path, filename)  
  
        # 读取Excel文件  
        df = pd.read_excel(file_path)  
  
        # 处理股票代码列  
        df['股票代码'] = df['股票代码'].astype(str).str.zfill(6)  
        df.to_excel(file_path, index=False)  # 如果需要覆盖原文件就使用这一行